# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy to baidu server - example page

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'feature-*'
      - 'fix-*'
      - 'hotfix-*'
      - 'refactor-*'
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'test/**'
      - 'examples/**'
      - 'build/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: build
      run: |
        npm i
        npm test
        npm run build:un-min --if-present
    - name: set ssh key # 临时设置 ssh key
      run: |
        mkdir -p ~/.ssh/
        echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{secrets.BAIDU_SERVER}} >> ~/.ssh/known_hosts
    - name: scp test files # 拷贝测试页面，到远程服务器
      run: |
        ## 获取当前分支名称，并创建一个同名的文件夹
        currentBranchName=`git branch | awk '$1 == "*"{print $2}'`
        mkdir $currentBranchName

        ## 将 dist examples 移到刚创建的文件夹之内
        mv dist/ $currentBranchName/dist/
        mv examples/ $currentBranchName/examples/

        ## 将该文件夹，及其所有文件，上传到服务器
        echo current branch name is: $currentBranchName
        ssh work@${{secrets.BAIDU_SERVER}} "rm -rf /home/work/wangEditor-team/v4-examples/$currentBranchName"
        scp -r ./$currentBranchName work@${{secrets.BAIDU_SERVER}}:/home/work/wangEditor-team/v4-examples/$currentBranchName
    - name: delete ssh key # 删除 ssh key
      run: rm -rf ~/.ssh/id_rsa
