# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: npm-publish and test

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm test
      - run: npm run build --if-present
      - run: npm run build:un-min --if-present
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-test:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{secrets.BAIDU_SERVER}} >> ~/.ssh/known_hosts
      - name: rebuild we-demo and scp
        run: |
          ## 下载 demo ，安装最新的插件，并重新打包
          git clone git@github.com:wangeditor-team/we-demo.git
          echo "--------------- git clone done ---------------"
          cd we-demo
          npm install
          echo "--------------- npm i done ---------------"
          npm install wangeditor@latest --save
          npm run prod
          echo "--------------- rebuild done ---------------"

          ## 将 dist 文件夹，重命名为 publish-npm-test ，并上传到服务器
          mv dist publish-npm-test
          ssh work@${{secrets.BAIDU_SERVER}} "rm -rf /home/work/wangEditor-team/v4-examples/publish-npm-test"
          scp -r ./publish-npm-test work@${{secrets.BAIDU_SERVER}}:/home/work/wangEditor-team/v4-examples/publish-npm-test
